# Generated by Django 2.2 on 2019-05-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20190430_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCounters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('ct1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_1', to='heroes.Hero')),
                ('ct2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_2', to='heroes.Hero')),
            ],
        ),
    ]
